name: lime_mobile_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6+2
  built_collection: ^4.3.2
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  flutter_dotenv: ^2.1.0
  image_picker: ^0.6.3+4
  url_launcher: ^5.4.2
  built_value: ^7.0.9
  provider: ^4.0.4
  sentry: ^3.0.1
  http: ^0.12.0+4
  intl: ^0.16.1
  uuid: ^2.0.4
  test: ^1.12.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.0.9
  build_web_compilers: ^2.9.0
  json_serializable: ^3.2.5
  build_runner: ^1.7.4
  mockito: ^4.1.1
  faker: ^1.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/poppins-light.ttf
           weight: 300
         - asset: assets/fonts/poppins-regular.ttf
           weight: 400
         - asset: assets/fonts/poppins-italic.ttf
           weight: 400
         - asset: assets/fonts/poppins-medium.ttf
           weight: 500
         - asset: assets/fonts/poppins-bold.ttf
           weight: 700
