class Strings {
  static final _App app = _App();
  static final _Dashboard dashboard = _Dashboard();
}

class _App {
  final String name = 'Lime';
  final String font = 'Poppins';
  final String userToken =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzExZmU1Nzk1MzVmMDAxN2RhOWU5NSIsIiRfXyI6eyJzdHJpY3RNb2RlIjp0cnVlLCJzZWxlY3RlZCI6e30sImdldHRlcnMiOnt9LCJfaWQiOiI1ZmMxMWZlNTc5NTM1ZjAwMTdkYTllOTUiLCJ3YXNQb3B1bGF0ZWQiOmZhbHNlLCJhY3RpdmVQYXRocyI6eyJwYXRocyI6eyJjb21wYW55IjoiaW5pdCIsInJvbGUiOiJpbml0IiwiZW1haWwiOiJpbml0IiwibGFzdG5hbWUiOiJpbml0IiwiZmlyc3RuYW1lIjoiaW5pdCIsInBhc3N3b3JkIjoiaW5pdCIsInVzZXJuYW1lIjoiaW5pdCIsIl9pZCI6ImluaXQiLCJjcmVhdGVkQXQiOiJpbml0IiwidXBkYXRlZEF0IjoiaW5pdCIsIl9fdiI6ImluaXQifSwic3RhdGVzIjp7Imlnbm9yZSI6e30sImRlZmF1bHQiOnt9LCJpbml0Ijp7Il9pZCI6dHJ1ZSwidXNlcm5hbWUiOnRydWUsInBhc3N3b3JkIjp0cnVlLCJmaXJzdG5hbWUiOnRydWUsImxhc3RuYW1lIjp0cnVlLCJlbWFpbCI6dHJ1ZSwicm9sZSI6dHJ1ZSwiY29tcGFueSI6dHJ1ZSwiY3JlYXRlZEF0Ijp0cnVlLCJ1cGRhdGVkQXQiOnRydWUsIl9fdiI6dHJ1ZX0sIm1vZGlmeSI6e30sInJlcXVpcmUiOnt9fSwic3RhdGVOYW1lcyI6WyJyZXF1aXJlIiwibW9kaWZ5IiwiaW5pdCIsImRlZmF1bHQiLCJpZ25vcmUiXX0sInBhdGhzVG9TY29wZXMiOnt9LCJjYWNoZWRSZXF1aXJlZCI6e30sIiRzZXRDYWxsZWQiOnt9LCJlbWl0dGVyIjp7Il9ldmVudHMiOnt9LCJfZXZlbnRzQ291bnQiOjAsIl9tYXhMaXN0ZW5lcnMiOjB9LCIkb3B0aW9ucyI6eyJza2lwSWQiOnRydWUsImlzTmV3IjpmYWxzZSwid2lsbEluaXQiOnRydWUsImRlZmF1bHRzIjp0cnVlfX0sImlzTmV3IjpmYWxzZSwiJGxvY2FscyI6e30sIiRvcCI6bnVsbCwiX2RvYyI6eyJfaWQiOiI1ZmMxMWZlNTc5NTM1ZjAwMTdkYTllOTUiLCJ1c2VybmFtZSI6IkJsZXNzZWQxMjE0IiwicGFzc3dvcmQiOiIkMmEkMDgkNG9pZG14ZE11M3dBalNLSXd2NmlTT21qb3lGZEtlMmF5T0tNcnhURFpDSkVMQlVFaXQwTG0iLCJmaXJzdG5hbWUiOiJMeWRpYSIsImxhc3RuYW1lIjoiRWRpYSIsImVtYWlsIjoiZ3JpcDIyOCIsInJvbGUiOiJMeWRpYSIsImNvbXBhbnkiOiJFZGlhIiwiY3JlYXRlZEF0IjoiMjAyMC0xMS0yN1QxNTo0ODo1My41MTRaIiwidXBkYXRlZEF0IjoiMjAyMC0xMS0yN1QxNTo0ODo1My41MTRaIiwiX192IjowfSwiJGluaXQiOnRydWUsImlhdCI6MTYwNjQ5MjE2MSwiZXhwIjoxNjE1MTMyMTYxfQ.gH7yR0GOnxQX_ubixSDq1Y8uYI6s3ptkBeYsK8l5opc';
}

class _Dashboard {
  final String home = 'Home';
  final String projects = 'Projects';
  final String surveys = 'Surveys';
  final String profile = 'Profile';
}
